
export const MEDICHAIN_ADDRESS = "0x89be79a62606F3f8D76eD27984bAbAa9910aD4df";
export const MEDICHAIN_ABI = [
  { "inputs": [], "stateMutability": "nonpayable", "type": "constructor" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "drugCode", "type": "bytes32" }, { "indexed": false, "internalType": "string", "name": "drugName", "type": "string" }, { "indexed": false, "internalType": "address", "name": "manufacturer", "type": "address" }], "name": "DrugAdded", "type": "event" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "bytes32", "name": "drugCode", "type": "bytes32" }, { "indexed": false, "internalType": "address", "name": "from", "type": "address" }, { "indexed": false, "internalType": "address", "name": "to", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "name": "DrugTransferred", "type": "event" },
  { "inputs": [{ "internalType": "bytes32", "name": "drugCode", "type": "bytes32" }, { "internalType": "string", "name": "name", "type": "string" }], "name": "addDrug", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }], "name": "drugs", "outputs": [{ "internalType": "string", "name": "drugName", "type": "string" }, { "internalType": "address", "name": "currentHolder", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "bytes32", "name": "drugCode", "type": "bytes32" }], "name": "getCurrentHolder", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "bytes32", "name": "drugCode", "type": "bytes32" }], "name": "getDrugHistory", "outputs": [{ "internalType": "address[]", "name": "", "type": "address[]" }, { "internalType": "uint256[]", "name": "", "type": "uint256[]" }, { "internalType": "string[]", "name": "", "type": "string[]" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "owner", "outputs": [{ "internalType": "address", "name": "", "type": "address" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "", "type": "address" }], "name": "roles", "outputs": [{ "internalType": "enum MediChain.Role", "name": "", "type": "uint8" }], "stateMutability": "view", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "userAddress", "type": "address" }, { "internalType": "enum MediChain.Role", "name": "newRole", "type": "uint8" }], "name": "setRole", "outputs": [], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "bytes32", "name": "drugCode", "type": "bytes32" }, { "internalType": "address", "name": "newHolder", "type": "address" }, { "internalType": "string", "name": "transferNotes", "type": "string" }], "name": "transferDrug", "outputs": [], "stateMutability": "nonpayable", "type": "function" }
] as const;
